### ISSUE TITLE
Carregar data da tarefa no editar

### ISSUE THREAD

**Issue by huogerac** [mrariel2011/TodoList#4]
A data não está sendo carregada no input ao editar tarefa.

Solução:
o `<input type="date"...` precisa de um value no formato `..value="2021-11-05">` este padrão tem o nome de isto format
se passar outro formato, ele será ignorado...

**Comment by huogerac** [comment]
@mrariel2011

**Comment by mrariel2011** [comment]
@huogerac Eu achei dessa forma também: {{ task.due_to|date:"Y-m-d" }}
De onde seria esse {{ task.due_to_iso }} que você colocou? Pertence a alguma biblioteca ou algo do tipo?

**Comment by huogerac** [comment]
Esta sua solucao fica mais elegante e menos codigo
